version: 0.2

phases:
  build:
    commands:
      - >
        aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS 
        --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - docker build -t $REPOSITORY_URI:latest .
      - docker push $REPOSITORY_URI:latest
  post_build:
    commands:
      - aws lambda update-function-code --function-name my_lambda --image-uri $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPOSITORY_URI:latest
artifacts:
  files:
    - "**/*"
  discard-paths: no
